[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "npm-9_x", "git"]
pythonVersion = "3.11"

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "npm ci --production=false"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "bash start.sh"