[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm ci --production=false"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
